# Use a lightweight Linux distribution as base image
FROM nginx:stable-perl 

# Copy the HTML file into the nginx web server's document root
COPY html/ /usr/share/nginx/html

# Expose port 80 for incoming web traffic
EXPOSE 80
